services:
  web-dev:
    build:
      context: .
    image: fixgo-dev:latest
    restart: unless-stopped
    env_file:
      - path: .env.dev
        required: true
      - path: .env.mongodb.dev
        required: true
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    expose:
      - "3000"
    networks:
      default:
        aliases:
          - hotfix-dev
      hotfix24-data:

  web-prod:
    build:
      context: .
    image: fixgo-prod:latest
    restart: unless-stopped
    env_file:
      - path: .env.production
        required: true
      - path: .env.mongodb.production
        required: true
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    expose:
      - "3000"
    networks:
      default:
        aliases:
          - hotfix-prod
      hotfix24-data:

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - web-dev
      - web-prod
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    name: fix-go-web_caddy_dev_data
  caddy_config:
    name: fix-go-web_caddy_dev_config

networks:
  hotfix24-data:
    external: true
